/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TripsRouteImport } from './routes/trips'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ScoutRouteImport } from './routes/scout'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as MapRouteImport } from './routes/map'
import { Route as ListPlaceRouteImport } from './routes/list-place'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlacesPlaceIdRouteImport } from './routes/places.$placeId'
import { Route as PlacesPlaceIdNavigateRouteImport } from './routes/places.$placeId.navigate'

const TripsRoute = TripsRouteImport.update({
  id: '/trips',
  path: '/trips',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutRoute = ScoutRouteImport.update({
  id: '/scout',
  path: '/scout',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const ListPlaceRoute = ListPlaceRouteImport.update({
  id: '/list-place',
  path: '/list-place',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesPlaceIdRoute = PlacesPlaceIdRouteImport.update({
  id: '/places/$placeId',
  path: '/places/$placeId',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacesPlaceIdNavigateRoute = PlacesPlaceIdNavigateRouteImport.update({
  id: '/navigate',
  path: '/navigate',
  getParentRoute: () => PlacesPlaceIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/list-place': typeof ListPlaceRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/scout': typeof ScoutRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips': typeof TripsRoute
  '/places/$placeId': typeof PlacesPlaceIdRouteWithChildren
  '/places/$placeId/navigate': typeof PlacesPlaceIdNavigateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/list-place': typeof ListPlaceRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/scout': typeof ScoutRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips': typeof TripsRoute
  '/places/$placeId': typeof PlacesPlaceIdRouteWithChildren
  '/places/$placeId/navigate': typeof PlacesPlaceIdNavigateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/list-place': typeof ListPlaceRoute
  '/map': typeof MapRoute
  '/profile': typeof ProfileRoute
  '/scout': typeof ScoutRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/trips': typeof TripsRoute
  '/places/$placeId': typeof PlacesPlaceIdRouteWithChildren
  '/places/$placeId/navigate': typeof PlacesPlaceIdNavigateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/list-place'
    | '/map'
    | '/profile'
    | '/scout'
    | '/settings'
    | '/sitemap.xml'
    | '/trips'
    | '/places/$placeId'
    | '/places/$placeId/navigate'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/list-place'
    | '/map'
    | '/profile'
    | '/scout'
    | '/settings'
    | '/sitemap.xml'
    | '/trips'
    | '/places/$placeId'
    | '/places/$placeId/navigate'
  id:
    | '__root__'
    | '/'
    | '/list-place'
    | '/map'
    | '/profile'
    | '/scout'
    | '/settings'
    | '/sitemap.xml'
    | '/trips'
    | '/places/$placeId'
    | '/places/$placeId/navigate'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ListPlaceRoute: typeof ListPlaceRoute
  MapRoute: typeof MapRoute
  ProfileRoute: typeof ProfileRoute
  ScoutRoute: typeof ScoutRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TripsRoute: typeof TripsRoute
  PlacesPlaceIdRoute: typeof PlacesPlaceIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/trips': {
      id: '/trips'
      path: '/trips'
      fullPath: '/trips'
      preLoaderRoute: typeof TripsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scout': {
      id: '/scout'
      path: '/scout'
      fullPath: '/scout'
      preLoaderRoute: typeof ScoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/list-place': {
      id: '/list-place'
      path: '/list-place'
      fullPath: '/list-place'
      preLoaderRoute: typeof ListPlaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$placeId': {
      id: '/places/$placeId'
      path: '/places/$placeId'
      fullPath: '/places/$placeId'
      preLoaderRoute: typeof PlacesPlaceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/places/$placeId/navigate': {
      id: '/places/$placeId/navigate'
      path: '/navigate'
      fullPath: '/places/$placeId/navigate'
      preLoaderRoute: typeof PlacesPlaceIdNavigateRouteImport
      parentRoute: typeof PlacesPlaceIdRoute
    }
  }
}

interface PlacesPlaceIdRouteChildren {
  PlacesPlaceIdNavigateRoute: typeof PlacesPlaceIdNavigateRoute
}

const PlacesPlaceIdRouteChildren: PlacesPlaceIdRouteChildren = {
  PlacesPlaceIdNavigateRoute: PlacesPlaceIdNavigateRoute,
}

const PlacesPlaceIdRouteWithChildren = PlacesPlaceIdRoute._addFileChildren(
  PlacesPlaceIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ListPlaceRoute: ListPlaceRoute,
  MapRoute: MapRoute,
  ProfileRoute: ProfileRoute,
  ScoutRoute: ScoutRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TripsRoute: TripsRoute,
  PlacesPlaceIdRoute: PlacesPlaceIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
